const POKEDEX_GEN7 = {
  name: "Alola",
  generation: 7,
  pokemon: [
    { id: 722, name: "Rowlet", type: "planta/volador", emoji: "🦉" },
    { id: 723, name: "Dartrix", type: "planta/volador", emoji: "🦉" },
    { id: 724, name: "Decidueye", type: "planta/fantasma", emoji: "🦉" },
    { id: 725, name: "Litten", type: "fuego", emoji: "🐱" },
    { id: 726, name: "Torracat", type: "fuego", emoji: "🐱" },
    { id: 727, name: "Incineroar", type: "fuego/siniestro", emoji: "🐯" },
    { id: 728, name: "Popplio", type: "agua", emoji: "🦭" },
    { id: 729, name: "Brionne", type: "agua", emoji: "🦭" },
    { id: 730, name: "Primarina", type: "agua/hada", emoji: "🦭" },
    { id: 731, name: "Pikipek", type: "normal/volador", emoji: "🐦" },
    { id: 732, name: "Trumbeak", type: "normal/volador", emoji: "🐦" },
    { id: 733, name: "Toucannon", type: "normal/volador", emoji: "🐦" },
    { id: 734, name: "Yungoos", type: "normal", emoji: "🐿️" },
    { id: 735, name: "Gumshoos", type: "normal", emoji: "🐿️" },
    { id: 736, name: "Grubbin", type: "bicho", emoji: "🐛" },
    { id: 737, name: "Charjabug", type: "bicho/eléctrico", emoji: "🐛" },
    { id: 738, name: "Vikavolt", type: "bicho/eléctrico", emoji: "🪲" },
    { id: 739, name: "Crabrawler", type: "lucha", emoji: "🦀" },
    { id: 740, name: "Crabominable", type: "lucha/hielo", emoji: "🦀" },
    { id: 741, name: "Oricorio", type: "fuego/volador", emoji: "🌺" },
    { id: 742, name: "Cutiefly", type: "bicho/hada", emoji: "🐝" },
    { id: 743, name: "Ribombee", type: "bicho/hada", emoji: "🐝" },
    { id: 744, name: "Rockruff", type: "roca", emoji: "🐕" },
    { id: 745, name: "Lycanroc", type: "roca", emoji: "🐺" },
    { id: 746, name: "Wishiwashi", type: "agua", emoji: "🐟" },
    { id: 747, name: "Mareanie", type: "veneno/agua", emoji: "🪼" },
    { id: 748, name: "Toxapex", type: "veneno/agua", emoji: "🪼" },
    { id: 749, name: "Mudbray", type: "tierra", emoji: "🐴" },
    { id: 750, name: "Mudsdale", type: "tierra", emoji: "🐴" },
    { id: 751, name: "Dewpider", type: "agua/bicho", emoji: "🕷️" },
    { id: 752, name: "Araquanid", type: "agua/bicho", emoji: "🕷️" },
    { id: 753, name: "Fomantis", type: "planta", emoji: "🌿" },
    { id: 754, name: "Lurantis", type: "planta", emoji: "🌿" },
    { id: 755, name: "Morelull", type: "planta/hada", emoji: "🍄" },
    { id: 756, name: "Shiinotic", type: "planta/hada", emoji: "🍄" },
    { id: 757, name: "Salandit", type: "veneno/fuego", emoji: "🦎" },
    { id: 758, name: "Salazzle", type: "veneno/fuego", emoji: "🦎" },
    { id: 759, name: "Stufful", type: "normal/lucha", emoji: "🐻" },
    { id: 760, name: "Bewear", type: "normal/lucha", emoji: "🐻" },
    { id: 761, name: "Bounsweet", type: "planta", emoji: "🌸" },
    { id: 762, name: "Steenee", type: "planta", emoji: "🌸" },
    { id: 763, name: "Tsareena", type: "planta", emoji: "🌸" },
    { id: 764, name: "Comfey", type: "hada", emoji: "🌺" },
    { id: 765, name: "Oranguru", type: "normal/psíquico", emoji: "🐵" },
    { id: 766, name: "Passimian", type: "lucha", emoji: "🐵" },
    { id: 767, name: "Wimpod", type: "bicho/agua", emoji: "🐛" },
    { id: 768, name: "Golisopod", type: "bicho/agua", emoji: "🦀" },
    { id: 769, name: "Sandygast", type: "fantasma/tierra", emoji: "🏖️" },
    { id: 770, name: "Palossand", type: "fantasma/tierra", emoji: "🏖️" },
    { id: 771, name: "Pyukumuku", type: "agua", emoji: "🥒" },
    { id: 772, name: "Type: Null", type: "normal", emoji: "🤖" },
    { id: 773, name: "Silvally", type: "normal", emoji: "🤖" },
    { id: 774, name: "Minior", type: "roca/volador", emoji: "⭐" },
    { id: 775, name: "Komala", type: "normal", emoji: "🐨" },
    { id: 776, name: "Turtonator", type: "fuego/dragón", emoji: "🐢" },
    { id: 777, name: "Togedemaru", type: "eléctrico/acero", emoji: "🦔" },
    { id: 778, name: "Mimikyu", type: "fantasma/hada", emoji: "👹" },
    { id: 779, name: "Bruxish", type: "agua/psíquico", emoji: "🐟" },
    { id: 780, name: "Drampa", type: "normal/dragón", emoji: "🐉" },
    { id: 781, name: "Dhelmise", type: "fantasma/planta", emoji: "⚓" },
    { id: 782, name: "Jangmo-o", type: "dragón", emoji: "🐉" },
    { id: 783, name: "Hakamo-o", type: "dragón/lucha", emoji: "🐉" },
    { id: 784, name: "Kommo-o", type: "dragón/lucha", emoji: "🐉" },
    { id: 785, name: "Tapu Koko", type: "eléctrico/hada", emoji: "⚡" },
    { id: 786, name: "Tapu Lele", type: "psíquico/hada", emoji: "🔮" },
    { id: 787, name: "Tapu Bulu", type: "planta/hada", emoji: "🌿" },
    { id: 788, name: "Tapu Fini", type: "agua/hada", emoji: "💧" },
    { id: 789, name: "Cosmog", type: "psíquico", emoji: "✨" },
    { id: 790, name: "Cosmoem", type: "psíquico", emoji: "✨" },
    { id: 791, name: "Solgaleo", type: "psíquico/acero", emoji: "☀️" },
    { id: 792, name: "Lunala", type: "psíquico/fantasma", emoji: "🌙" },
    { id: 793, name: "Nihilego", type: "roca/veneno", emoji: "🪼" },
    { id: 794, name: "Buzzwole", type: "bicho/lucha", emoji: "💪" },
    { id: 795, name: "Pheromosa", type: "bicho/lucha", emoji: "🦗" },
    { id: 796, name: "Xurkitree", type: "eléctrico", emoji: "⚡" },
    { id: 797, name: "Celesteela", type: "acero/volador", emoji: "🚀" },
    { id: 798, name: "Kartana", type: "planta/acero", emoji: "🗡️" },
    { id: 799, name: "Guzzlord", type: "siniestro/dragón", emoji: "🐲" },
    { id: 800, name: "Necrozma", type: "psíquico", emoji: "💎" },
    { id: 801, name: "Magearna", type: "acero/hada", emoji: "🤖" },
    { id: 802, name: "Marshadow", type: "lucha/fantasma", emoji: "👻" },
    { id: 803, name: "Poipole", type: "veneno", emoji: "💜" },
    { id: 804, name: "Naganadel", type: "veneno/dragón", emoji: "💜" },
    { id: 805, name: "Stakataka", type: "roca/acero", emoji: "🧱" },
    { id: 806, name: "Blacephalon", type: "fuego/fantasma", emoji: "💥" },
    { id: 807, name: "Zeraora", type: "eléctrico", emoji: "⚡" },
    { id: 808, name: "Meltan", type: "acero", emoji: "🔩" },
    { id: 809, name: "Melmetal", type: "acero", emoji: "🔩" }
  ]
};
