const POKEDEX_GEN9 = {
  name: "Paldea",
  generation: 9,
  pokemon: [
    { id: 906, name: "Sprigatito", type: "planta", emoji: "🌸" },
    { id: 907, name: "Floragato", type: "planta", emoji: "🌸" },
    { id: 908, name: "Meowscarada", type: "planta/siniestro", emoji: "🌸" },
    { id: 909, name: "Fuecoco", type: "fuego", emoji: "🦷" },
    { id: 910, name: "Crocalor", type: "fuego", emoji: "🦷" },
    { id: 911, name: "Skeledirge", type: "fuego/fantasma", emoji: "🦷" },
    { id: 912, name: "Quaxly", type: "agua", emoji: "🦆" },
    { id: 913, name: "Quaxwell", type: "agua", emoji: "🦆" },
    { id: 914, name: "Quaquaval", type: "agua/lucha", emoji: "🦆" },
    { id: 915, name: "Lechonk", type: "normal", emoji: "🐷" },
    { id: 916, name: "Oinkologne", type: "normal", emoji: "🐷" },
    { id: 917, name: "Tarountula", type: "bicho", emoji: "🕷️" },
    { id: 918, name: "Spidops", type: "bicho", emoji: "🕷️" },
    { id: 919, name: "Nymble", type: "bicho", emoji: "🦗" },
    { id: 920, name: "Lokix", type: "bicho/siniestro", emoji: "🦗" },
    { id: 921, name: "Pawmi", type: "eléctrico", emoji: "⚡" },
    { id: 922, name: "Pawmo", type: "eléctrico/lucha", emoji: "⚡" },
    { id: 923, name: "Pawmot", type: "eléctrico/lucha", emoji: "⚡" },
    { id: 924, name: "Tandemaus", type: "normal", emoji: "🐭" },
    { id: 925, name: "Maushold", type: "normal", emoji: "🐭" },
    { id: 926, name: "Fidough", type: "hada", emoji: "🐕" },
    { id: 927, name: "Dachsbun", type: "hada", emoji: "🐕" },
    { id: 928, name: "Smoliv", type: "planta/normal", emoji: "🫒" },
    { id: 929, name: "Dolliv", type: "planta/normal", emoji: "🫒" },
    { id: 930, name: "Arboliva", type: "planta/normal", emoji: "🫒" },
    { id: 931, name: "Squawkabilly", type: "normal/volador", emoji: "🐦" },
    { id: 932, name: "Nacli", type: "roca", emoji: "🧂" },
    { id: 933, name: "Naclstack", type: "roca", emoji: "🧂" },
    { id: 934, name: "Garganacl", type: "roca", emoji: "🧂" },
    { id: 935, name: "Charcadet", type: "fuego", emoji: "🔥" },
    { id: 936, name: "Armarouge", type: "fuego/psíquico", emoji: "🔥" },
    { id: 937, name: "Ceruledge", type: "fuego/fantasma", emoji: "🔥" },
    { id: 938, name: "Tadbulb", type: "eléctrico", emoji: "💡" },
    { id: 939, name: "Bellibolt", type: "eléctrico", emoji: "🐸" },
    { id: 940, name: "Wattrel", type: "eléctrico/volador", emoji: "🐦" },
    { id: 941, name: "Kilowattrel", type: "eléctrico/volador", emoji: "🐦" },
    { id: 942, name: "Maschiff", type: "siniestro", emoji: "🐕" },
    { id: 943, name: "Mabosstiff", type: "siniestro", emoji: "🐕" },
    { id: 944, name: "Shroodle", type: "veneno/normal", emoji: "🐭" },
    { id: 945, name: "Grafaiai", type: "veneno/normal", emoji: "🐵" },
    { id: 946, name: "Bramblin", type: "planta/fantasma", emoji: "🌿" },
    { id: 947, name: "Brambleghast", type: "planta/fantasma", emoji: "🌿" },
    { id: 948, name: "Toedscool", type: "tierra/planta", emoji: "🍄" },
    { id: 949, name: "Toedscruel", type: "tierra/planta", emoji: "🍄" },
    { id: 950, name: "Klawf", type: "roca", emoji: "🦀" },
    { id: 951, name: "Capsakid", type: "planta", emoji: "🌶️" },
    { id: 952, name: "Scovillain", type: "planta/fuego", emoji: "🌶️" },
    { id: 953, name: "Rellor", type: "bicho", emoji: "🪲" },
    { id: 954, name: "Rabsca", type: "bicho/psíquico", emoji: "🪲" },
    { id: 955, name: "Flittle", type: "psíquico", emoji: "🐦" },
    { id: 956, name: "Espathra", type: "psíquico", emoji: "🦚" },
    { id: 957, name: "Tinkatink", type: "hada/acero", emoji: "🔨" },
    { id: 958, name: "Tinkatuff", type: "hada/acero", emoji: "🔨" },
    { id: 959, name: "Tinkaton", type: "hada/acero", emoji: "🔨" },
    { id: 960, name: "Wiglett", type: "agua", emoji: "🐍" },
    { id: 961, name: "Wugtrio", type: "agua", emoji: "🐍" },
    { id: 962, name: "Bombirdier", type: "volador/siniestro", emoji: "🐦" },
    { id: 963, name: "Finizen", type: "agua", emoji: "🐬" },
    { id: 964, name: "Palafin", type: "agua", emoji: "🐬" },
    { id: 965, name: "Varoom", type: "acero/veneno", emoji: "🚗" },
    { id: 966, name: "Revavroom", type: "acero/veneno", emoji: "🚗" },
    { id: 967, name: "Cyclizar", type: "dragón/normal", emoji: "🦎" },
    { id: 968, name: "Orthworm", type: "acero", emoji: "🐍" },
    { id: 969, name: "Glimmet", type: "roca/veneno", emoji: "💎" },
    { id: 970, name: "Glimmora", type: "roca/veneno", emoji: "💎" },
    { id: 971, name: "Greavard", type: "fantasma", emoji: "🐕" },
    { id: 972, name: "Houndstone", type: "fantasma", emoji: "🐕" },
    { id: 973, name: "Flamigo", type: "volador/lucha", emoji: "🦩" },
    { id: 974, name: "Cetoddle", type: "hielo", emoji: "🐋" },
    { id: 975, name: "Cetitan", type: "hielo", emoji: "🐋" },
    { id: 976, name: "Veluza", type: "agua/psíquico", emoji: "🐟" },
    { id: 977, name: "Dondozo", type: "agua", emoji: "🐟" },
    { id: 978, name: "Tatsugiri", type: "dragón/agua", emoji: "🍣" },
    { id: 979, name: "Annihilape", type: "lucha/fantasma", emoji: "🐒" },
    { id: 980, name: "Clodsire", type: "veneno/tierra", emoji: "🐸" },
    { id: 981, name: "Farigiraf", type: "normal/psíquico", emoji: "🦒" },
    { id: 982, name: "Dudunsparce", type: "normal", emoji: "🐍" },
    { id: 983, name: "Kingambit", type: "siniestro/acero", emoji: "⚔️" },
    { id: 984, name: "Great Tusk", type: "tierra/lucha", emoji: "🐘" },
    { id: 985, name: "Scream Tail", type: "hada/psíquico", emoji: "🎀" },
    { id: 986, name: "Brute Bonnet", type: "planta/siniestro", emoji: "🍄" },
    { id: 987, name: "Flutter Mane", type: "fantasma/hada", emoji: "👻" },
    { id: 988, name: "Slither Wing", type: "bicho/lucha", emoji: "🦋" },
    { id: 989, name: "Sandy Shocks", type: "eléctrico/tierra", emoji: "⚡" },
    { id: 990, name: "Iron Treads", type: "tierra/acero", emoji: "🤖" },
    { id: 991, name: "Iron Bundle", type: "hielo/agua", emoji: "🤖" },
    { id: 992, name: "Iron Hands", type: "lucha/eléctrico", emoji: "🤖" },
    { id: 993, name: "Iron Jugulis", type: "siniestro/volador", emoji: "🤖" },
    { id: 994, name: "Iron Moth", type: "fuego/veneno", emoji: "🤖" },
    { id: 995, name: "Iron Thorns", type: "roca/eléctrico", emoji: "🤖" },
    { id: 996, name: "Frigibax", type: "dragón/hielo", emoji: "❄️" },
    { id: 997, name: "Arctibax", type: "dragón/hielo", emoji: "❄️" },
    { id: 998, name: "Baxcalibur", type: "dragón/hielo", emoji: "🐉" },
    { id: 999, name: "Gimmighoul", type: "fantasma", emoji: "💰" },
    { id: 1000, name: "Gholdengo", type: "acero/fantasma", emoji: "💰" },
    { id: 1001, name: "Wo-Chien", type: "siniestro/planta", emoji: "🌿" },
    { id: 1002, name: "Chien-Pao", type: "siniestro/hielo", emoji: "❄️" },
    { id: 1003, name: "Ting-Lu", type: "siniestro/tierra", emoji: "🏺" },
    { id: 1004, name: "Chi-Yu", type: "siniestro/fuego", emoji: "🔥" },
    { id: 1005, name: "Roaring Moon", type: "dragón/siniestro", emoji: "🐉" },
    { id: 1006, name: "Iron Valiant", type: "hada/lucha", emoji: "🤖" },
    { id: 1007, name: "Koraidon", type: "dragón/lucha", emoji: "🐉" },
    { id: 1008, name: "Miraidon", type: "dragón/eléctrico", emoji: "🐉" },
    { id: 1009, name: "Walking Wake", type: "agua/dragón", emoji: "🐉" },
    { id: 1010, name: "Iron Leaves", type: "planta/psíquico", emoji: "🤖" },
    { id: 1011, name: "Dipplin", type: "planta/dragón", emoji: "🍎" },
    { id: 1012, name: "Poltchageist", type: "planta/fantasma", emoji: "🍵" },
    { id: 1013, name: "Sinistcha", type: "planta/fantasma", emoji: "🍵" },
    { id: 1014, name: "Okidogi", type: "veneno/lucha", emoji: "🐕" },
    { id: 1015, name: "Munkidori", type: "veneno/psíquico", emoji: "🐵" },
    { id: 1016, name: "Fezandipiti", type: "veneno/hada", emoji: "🐦" },
    { id: 1017, name: "Ogerpon", type: "planta", emoji: "👹" },
    { id: 1018, name: "Archaludon", type: "acero/dragón", emoji: "🔩" },
    { id: 1019, name: "Hydrapple", type: "planta/dragón", emoji: "🍎" },
    { id: 1020, name: "Gouging Fire", type: "fuego/dragón", emoji: "🔥" },
    { id: 1021, name: "Raging Bolt", type: "eléctrico/dragón", emoji: "⚡" },
    { id: 1022, name: "Iron Boulder", type: "roca/psíquico", emoji: "🤖" },
    { id: 1023, name: "Iron Crown", type: "acero/psíquico", emoji: "🤖" },
    { id: 1024, name: "Terapagos", type: "normal", emoji: "🐢" },
    { id: 1025, name: "Pecharunt", type: "veneno/fantasma", emoji: "🍑" }
  ]
};
