const POKEMON_HP_GEN9 = [
  { id: 906, name: "Sprigatito", baseHP: 40, evolutionLevel: 16 },
  { id: 907, name: "Floragato", baseHP: 61, evolutionLevel: 36 },
  { id: 908, name: "Meowscarada", baseHP: 76, evolutionLevel: null },
  { id: 909, name: "Fuecoco", baseHP: 67, evolutionLevel: 16 },
  { id: 910, name: "Crocalor", baseHP: 81, evolutionLevel: 36 },
  { id: 911, name: "Skeledirge", baseHP: 104, evolutionLevel: null },
  { id: 912, name: "Quaxly", baseHP: 55, evolutionLevel: 16 },
  { id: 913, name: "Quaxwell", baseHP: 70, evolutionLevel: 36 },
  { id: 914, name: "Quaquaval", baseHP: 85, evolutionLevel: null },
  { id: 915, name: "Lechonk", baseHP: 54, evolutionLevel: 18 },
  { id: 916, name: "Oinkologne", baseHP: 110, evolutionLevel: null },
  { id: 917, name: "Tarountula", baseHP: 35, evolutionLevel: 15 },
  { id: 918, name: "Spidops", baseHP: 60, evolutionLevel: null },
  { id: 919, name: "Nymble", baseHP: 33, evolutionLevel: 24 },
  { id: 920, name: "Lokix", baseHP: 71, evolutionLevel: null },
  { id: 921, name: "Pawmi", baseHP: 45, evolutionLevel: 18 },
  { id: 922, name: "Pawmo", baseHP: 60, evolutionLevel: 32 },
  { id: 923, name: "Pawmot", baseHP: 70, evolutionLevel: null },
  { id: 924, name: "Tandemaus", baseHP: 50, evolutionLevel: 25 },
  { id: 925, name: "Maushold", baseHP: 74, evolutionLevel: null },
  { id: 926, name: "Fidough", baseHP: 37, evolutionLevel: 26 },
  { id: 927, name: "Dachsbun", baseHP: 57, evolutionLevel: null },
  { id: 928, name: "Smoliv", baseHP: 41, evolutionLevel: 25 },
  { id: 929, name: "Dolliv", baseHP: 52, evolutionLevel: 35 },
  { id: 930, name: "Arboliva", baseHP: 78, evolutionLevel: null },
  { id: 931, name: "Squawkabilly", baseHP: 82, evolutionLevel: null },
  { id: 932, name: "Nacli", baseHP: 55, evolutionLevel: 24 },
  { id: 933, name: "Naclstack", baseHP: 60, evolutionLevel: 38 },
  { id: 934, name: "Garganacl", baseHP: 100, evolutionLevel: null },
  { id: 935, name: "Charcadet", baseHP: 40, evolutionLevel: null },
  { id: 936, name: "Armarouge", baseHP: 85, evolutionLevel: null },
  { id: 937, name: "Ceruledge", baseHP: 75, evolutionLevel: null },
  { id: 938, name: "Tadbulb", baseHP: 61, evolutionLevel: null },
  { id: 939, name: "Bellibolt", baseHP: 109, evolutionLevel: null },
  { id: 940, name: "Wattrel", baseHP: 40, evolutionLevel: 25 },
  { id: 941, name: "Kilowattrel", baseHP: 70, evolutionLevel: null },
  { id: 942, name: "Maschiff", baseHP: 60, evolutionLevel: 30 },
  { id: 943, name: "Mabosstiff", baseHP: 80, evolutionLevel: null },
  { id: 944, name: "Shroodle", baseHP: 40, evolutionLevel: 28 },
  { id: 945, name: "Grafaiai", baseHP: 63, evolutionLevel: null },
  { id: 946, name: "Bramblin", baseHP: 40, evolutionLevel: null },
  { id: 947, name: "Brambleghast", baseHP: 55, evolutionLevel: null },
  { id: 948, name: "Toedscool", baseHP: 40, evolutionLevel: 30 },
  { id: 949, name: "Toedscruel", baseHP: 80, evolutionLevel: null },
  { id: 950, name: "Klawf", baseHP: 70, evolutionLevel: null },
  { id: 951, name: "Capsakid", baseHP: 50, evolutionLevel: null },
  { id: 952, name: "Scovillain", baseHP: 65, evolutionLevel: null },
  { id: 953, name: "Rellor", baseHP: 41, evolutionLevel: null },
  { id: 954, name: "Rabsca", baseHP: 75, evolutionLevel: null },
  { id: 955, name: "Flittle", baseHP: 30, evolutionLevel: 35 },
  { id: 956, name: "Espathra", baseHP: 95, evolutionLevel: null },
  { id: 957, name: "Tinkatink", baseHP: 50, evolutionLevel: 24 },
  { id: 958, name: "Tinkatuff", baseHP: 65, evolutionLevel: 38 },
  { id: 959, name: "Tinkaton", baseHP: 85, evolutionLevel: null },
  { id: 960, name: "Wiglett", baseHP: 10, evolutionLevel: 26 },
  { id: 961, name: "Wugtrio", baseHP: 35, evolutionLevel: null },
  { id: 962, name: "Bombirdier", baseHP: 70, evolutionLevel: null },
  { id: 963, name: "Finizen", baseHP: 70, evolutionLevel: 38 },
  { id: 964, name: "Palafin", baseHP: 100, evolutionLevel: null },
  { id: 965, name: "Varoom", baseHP: 45, evolutionLevel: 40 },
  { id: 966, name: "Revavroom", baseHP: 80, evolutionLevel: null },
  { id: 967, name: "Cyclizar", baseHP: 70, evolutionLevel: null },
  { id: 968, name: "Orthworm", baseHP: 70, evolutionLevel: null },
  { id: 969, name: "Glimmet", baseHP: 48, evolutionLevel: 35 },
  { id: 970, name: "Glimmora", baseHP: 83, evolutionLevel: null },
  { id: 971, name: "Greavard", baseHP: 65, evolutionLevel: 30 },
  { id: 972, name: "Houndstone", baseHP: 72, evolutionLevel: null },
  { id: 973, name: "Flamigo", baseHP: 82, evolutionLevel: null },
  { id: 974, name: "Cetoddle", baseHP: 108, evolutionLevel: null },
  { id: 975, name: "Cetitan", baseHP: 170, evolutionLevel: null },
  { id: 976, name: "Veluza", baseHP: 90, evolutionLevel: null },
  { id: 977, name: "Dondozo", baseHP: 150, evolutionLevel: null },
  { id: 978, name: "Tatsugiri", baseHP: 68, evolutionLevel: null },
  { id: 979, name: "Annihilape", baseHP: 110, evolutionLevel: null },
  { id: 980, name: "Clodsire", baseHP: 130, evolutionLevel: null },
  { id: 981, name: "Farigiraf", baseHP: 120, evolutionLevel: null },
  { id: 982, name: "Dudunsparce", baseHP: 125, evolutionLevel: null },
  { id: 983, name: "Kingambit", baseHP: 100, evolutionLevel: null },
  { id: 984, name: "Great Tusk", baseHP: 115, evolutionLevel: null },
  { id: 985, name: "Scream Tail", baseHP: 115, evolutionLevel: null },
  { id: 986, name: "Brute Bonnet", baseHP: 111, evolutionLevel: null },
  { id: 987, name: "Flutter Mane", baseHP: 55, evolutionLevel: null },
  { id: 988, name: "Slither Wing", baseHP: 85, evolutionLevel: null },
  { id: 989, name: "Sandy Shocks", baseHP: 85, evolutionLevel: null },
  { id: 990, name: "Iron Treads", baseHP: 90, evolutionLevel: null },
  { id: 991, name: "Iron Bundle", baseHP: 56, evolutionLevel: null },
  { id: 992, name: "Iron Hands", baseHP: 154, evolutionLevel: null },
  { id: 993, name: "Iron Jugulis", baseHP: 94, evolutionLevel: null },
  { id: 994, name: "Iron Moth", baseHP: 80, evolutionLevel: null },
  { id: 995, name: "Iron Thorns", baseHP: 100, evolutionLevel: null },
  { id: 996, name: "Frigibax", baseHP: 65, evolutionLevel: 35 },
  { id: 997, name: "Arctibax", baseHP: 90, evolutionLevel: 54 },
  { id: 998, name: "Baxcalibur", baseHP: 115, evolutionLevel: null },
  { id: 999, name: "Gimmighoul", baseHP: 45, evolutionLevel: null },
  { id: 1000, name: "Gholdengo", baseHP: 87, evolutionLevel: null },
  { id: 1001, name: "Wo-Chien", baseHP: 85, evolutionLevel: null },
  { id: 1002, name: "Chien-Pao", baseHP: 80, evolutionLevel: null },
  { id: 1003, name: "Ting-Lu", baseHP: 155, evolutionLevel: null },
  { id: 1004, name: "Chi-Yu", baseHP: 55, evolutionLevel: null },
  { id: 1005, name: "Roaring Moon", baseHP: 105, evolutionLevel: null },
  { id: 1006, name: "Iron Valiant", baseHP: 74, evolutionLevel: null },
  { id: 1007, name: "Koraidon", baseHP: 100, evolutionLevel: null },
  { id: 1008, name: "Miraidon", baseHP: 100, evolutionLevel: null },
  { id: 1009, name: "Walking Wake", baseHP: 99, evolutionLevel: null },
  { id: 1010, name: "Iron Leaves", baseHP: 90, evolutionLevel: null },
  { id: 1011, name: "Dipplin", baseHP: 80, evolutionLevel: null },
  { id: 1012, name: "Poltchageist", baseHP: 40, evolutionLevel: null },
  { id: 1013, name: "Sinistcha", baseHP: 71, evolutionLevel: null },
  { id: 1014, name: "Okidogi", baseHP: 88, evolutionLevel: null },
  { id: 1015, name: "Munkidori", baseHP: 88, evolutionLevel: null },
  { id: 1016, name: "Fezandipiti", baseHP: 88, evolutionLevel: null },
  { id: 1017, name: "Ogerpon", baseHP: 80, evolutionLevel: null },
  { id: 1018, name: "Archaludon", baseHP: 90, evolutionLevel: null },
  { id: 1019, name: "Hydrapple", baseHP: 106, evolutionLevel: null },
  { id: 1020, name: "Gouging Fire", baseHP: 105, evolutionLevel: null },
  { id: 1021, name: "Raging Bolt", baseHP: 125, evolutionLevel: null },
  { id: 1022, name: "Iron Boulder", baseHP: 90, evolutionLevel: null },
  { id: 1023, name: "Iron Crown", baseHP: 90, evolutionLevel: null },
  { id: 1024, name: "Terapagos", baseHP: 90, evolutionLevel: null },
  { id: 1025, name: "Pecharunt", baseHP: 88, evolutionLevel: null }
];
